# /export/.bowtie.yml

development:
  permits:
    plans:
      - Tester
      - Startup - Pro

staging:
  permits:
    plans:
      - Tester
      - Startup - Pro

master:
  permits:
    plans:
      - Tester
      - Startup - Pro
